name: build docker containers and push to Dockerhub

on:
    push:
        branches: ["main"]

jobs:
    containerize-edit-settings:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2
              with:
                  ref: build

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: ./docker
                  file: ./settings.Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pmd-edit-settings:latest

    containerize-onedrive:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2
              with:
                  ref: build

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: ./docker
                  file: ./Onedrive.Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/custom-onedrive:latest

    containerize-polito-material-download:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2
              with:
                  ref: build

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./docker/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/polito-material-downloader:latest
